name: publish

on:
  release:
    types: [published]

jobs:
  publish-bin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token ${{ secrets.CRATES_TOKEN }}
  publish-lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./waybackmachine-client
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token ${{ secrets.CRATES_TOKEN }}
