name: test-and-check

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-bin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build binary
      run: cargo build --verbose
  test-lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./waybackmachine-client
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --workspace --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run linting
      run: cargo clippy --all --all-targets --all-features -- -D warnings
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run format
        run: cargo fmt --all -- --check
